/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminFooter: typeof import('./src/components/admin/footer/index.vue')['default']
    AdminSidebar: typeof import('./src/components/admin/sidebar/index.vue')['default']
    AdminTopNav: typeof import('./src/components/admin/top-nav/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
