/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/blog/': RouteRecordInfo<'/admin/blog/', '/admin/blog', Record<never, never>, Record<never, never>>,
    '/admin/blog/list': RouteRecordInfo<'/admin/blog/list', '/admin/blog/list', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/list': RouteRecordInfo<'/admin/dashboard/list', '/admin/dashboard/list', Record<never, never>, Record<never, never>>,
    '/admin/note/': RouteRecordInfo<'/admin/note/', '/admin/note', Record<never, never>, Record<never, never>>,
    '/admin/note/list': RouteRecordInfo<'/admin/note/list', '/admin/note/list', Record<never, never>, Record<never, never>>,
    '/admin/project/': RouteRecordInfo<'/admin/project/', '/admin/project', Record<never, never>, Record<never, never>>,
    '/admin/project/list': RouteRecordInfo<'/admin/project/list', '/admin/project/list', Record<never, never>, Record<never, never>>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/articles': RouteRecordInfo<'/blog/articles', '/blog/articles', Record<never, never>, Record<never, never>>,
    '/blog/tags': RouteRecordInfo<'/blog/tags', '/blog/tags', Record<never, never>, Record<never, never>>,
    '/collection/': RouteRecordInfo<'/collection/', '/collection', Record<never, never>, Record<never, never>>,
    '/collection/list': RouteRecordInfo<'/collection/list', '/collection/list', Record<never, never>, Record<never, never>>,
    '/interview/': RouteRecordInfo<'/interview/', '/interview', Record<never, never>, Record<never, never>>,
    '/interview/question-list': RouteRecordInfo<'/interview/question-list', '/interview/question-list', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
  }
}
