/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/blog/': RouteRecordInfo<'/admin/blog/', '/admin/blog', Record<never, never>, Record<never, never>>,
    '/admin/blog/list': RouteRecordInfo<'/admin/blog/list', '/admin/blog/list', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/list': RouteRecordInfo<'/admin/dashboard/list', '/admin/dashboard/list', Record<never, never>, Record<never, never>>,
    '/admin/note/': RouteRecordInfo<'/admin/note/', '/admin/note', Record<never, never>, Record<never, never>>,
    '/admin/note/list': RouteRecordInfo<'/admin/note/list', '/admin/note/list', Record<never, never>, Record<never, never>>,
    '/admin/project/': RouteRecordInfo<'/admin/project/', '/admin/project', Record<never, never>, Record<never, never>>,
    '/admin/project/list': RouteRecordInfo<'/admin/project/list', '/admin/project/list', Record<never, never>, Record<never, never>>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/articles': RouteRecordInfo<'/blog/articles', '/blog/articles', Record<never, never>, Record<never, never>>,
    '/blog/tags': RouteRecordInfo<'/blog/tags', '/blog/tags', Record<never, never>, Record<never, never>>,
    '/collection/': RouteRecordInfo<'/collection/', '/collection', Record<never, never>, Record<never, never>>,
    '/collection/list': RouteRecordInfo<'/collection/list', '/collection/list', Record<never, never>, Record<never, never>>,
    '/examples/custom-ref/demo-01': RouteRecordInfo<'/examples/custom-ref/demo-01', '/examples/custom-ref/demo-01', Record<never, never>, Record<never, never>>,
    '/examples/element-plus/custom-column/': RouteRecordInfo<'/examples/element-plus/custom-column/', '/examples/element-plus/custom-column', Record<never, never>, Record<never, never>>,
    '/examples/element-plus/select/1': RouteRecordInfo<'/examples/element-plus/select/1', '/examples/element-plus/select/1', Record<never, never>, Record<never, never>>,
    '/examples/element-plus/slider/1': RouteRecordInfo<'/examples/element-plus/slider/1', '/examples/element-plus/slider/1', Record<never, never>, Record<never, never>>,
    '/examples/flow/flow-01/': RouteRecordInfo<'/examples/flow/flow-01/', '/examples/flow/flow-01', Record<never, never>, Record<never, never>>,
    '/examples/flow/flow-02/': RouteRecordInfo<'/examples/flow/flow-02/', '/examples/flow/flow-02', Record<never, never>, Record<never, never>>,
    '/examples/gsap/template': RouteRecordInfo<'/examples/gsap/template', '/examples/gsap/template', Record<never, never>, Record<never, never>>,
    '/examples/template': RouteRecordInfo<'/examples/template', '/examples/template', Record<never, never>, Record<never, never>>,
    '/examples/template-jsx': RouteRecordInfo<'/examples/template-jsx', '/examples/template-jsx', Record<never, never>, Record<never, never>>,
    '/examples/ts/props/': RouteRecordInfo<'/examples/ts/props/', '/examples/ts/props', Record<never, never>, Record<never, never>>,
    '/examples/ts/props/MyCom': RouteRecordInfo<'/examples/ts/props/MyCom', '/examples/ts/props/MyCom', Record<never, never>, Record<never, never>>,
    '/examples/ts/useTemplateRef/': RouteRecordInfo<'/examples/ts/useTemplateRef/', '/examples/ts/useTemplateRef', Record<never, never>, Record<never, never>>,
    '/examples/ts/useTemplateRef/MyCom': RouteRecordInfo<'/examples/ts/useTemplateRef/MyCom', '/examples/ts/useTemplateRef/MyCom', Record<never, never>, Record<never, never>>,
    '/examples/turbo-console/test1': RouteRecordInfo<'/examples/turbo-console/test1', '/examples/turbo-console/test1', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
  }
}
